M48
; DRILL file {KiCad (6.0.7)} date Sat Jan 28 12:42:47 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-28T12:42:47-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X134.0Y-74.04
X143.0Y-74.04
T2
X109.87Y-70.96
X109.87Y-123.96
X185.87Y-70.96
X185.87Y-123.96
T0
M30
