M48
; DRILL file {KiCad 7.0.2} date Mon Jun  5 15:01:05 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-05T15:01:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X117.1Y-43.225
X126.1Y-43.225
T2
X87.852Y-97.75
X88.0Y-43.0
X156.852Y-97.75
X157.0Y-43.0
T0
M30
