M48
; DRILL file {KiCad 8.0.0} date 2025-04-17T02:07:29-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-17T02:07:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X177.36Y-63.4
X177.36Y-75.4
T2
X103.2Y-52.2
X103.2Y-103.15
X175.3Y-52.2
X175.3Y-103.15
M30
